TASK: PE
TYPE: idx_relative_concat

LOADER:
    loader.idx_relative
MODEL_TYPE:
    model.idx.concat


PARAMETERS:
    BATCH_SIZE: 256
    LEARNING_RATE: 0.005
    WEIGHT_DECAY: 0.000001

MODEL:
    RESNET:
        NUM_LAYERS: 50
        DROPOUT_RATE: 0.5
    LSTM:
        NUM_LAYERS: 2
        HIDDEN_DIM: 128
        BIDIRECTIONAL: True
    FC:
        NUM_CLASSES: 5
        
